// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiW4f4k2mlsxJexnlBpOMWx6gnrBnAsCg',
    appId: '1:1762801457:web:a19f623358dcc8322c2210',
    messagingSenderId: '1762801457',
    projectId: 'demotalkasecond',
    authDomain: 'demotalkasecond.firebaseapp.com',
    storageBucket: 'demotalkasecond.firebasestorage.app',
    measurementId: 'G-5YVS3EH6FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHNgj96Ry8C-X4axj7RQ8JF1rWHGtpBU',
    appId: '1:1762801457:android:a5f41d86024015f62c2210',
    messagingSenderId: '1762801457',
    projectId: 'demotalkasecond',
    storageBucket: 'demotalkasecond.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtvbV_NZSusAI_GLZNQPAwyfRc6htbyHM',
    appId: '1:1762801457:ios:33bb6c79263ddc8b2c2210',
    messagingSenderId: '1762801457',
    projectId: 'demotalkasecond',
    storageBucket: 'demotalkasecond.firebasestorage.app',
    iosBundleId: 'com.example.demotalkasecond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtvbV_NZSusAI_GLZNQPAwyfRc6htbyHM',
    appId: '1:1762801457:ios:33bb6c79263ddc8b2c2210',
    messagingSenderId: '1762801457',
    projectId: 'demotalkasecond',
    storageBucket: 'demotalkasecond.firebasestorage.app',
    iosBundleId: 'com.example.demotalkasecond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiW4f4k2mlsxJexnlBpOMWx6gnrBnAsCg',
    appId: '1:1762801457:web:d55661e7c04bd5b62c2210',
    messagingSenderId: '1762801457',
    projectId: 'demotalkasecond',
    authDomain: 'demotalkasecond.firebaseapp.com',
    storageBucket: 'demotalkasecond.firebasestorage.app',
    measurementId: 'G-XMHQH47H1Z',
  );

}